# NUMPY 

# Welcome to numpy :

 **what is numpy :**
    

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

# Installation of NumPy
   - If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

   - Install it using this command:

   - pip install numpy

# Import NumPy
- Once NumPy is installed, import it in your applications by adding the import keyword:

In [1]:
import numpy as np

NumPy is usually imported under the np alias.

In [2]:
import numpy 
arr=numpy.array([i for i in range (19)])

In [3]:
my_array=np.array([1,2,3,4,5])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
print(my_array)

[1 2 3 4 5]


In [6]:
my_array=np.array([1,2,30000,4,5] , np.int32)    #here we can manage a memory using np.int64

In [7]:
my_array

array([    1,     2, 30000,     4,     5])

In [8]:
my_array[0:3]

array([    1,     2, 30000])

In [9]:
my_array[-1]

5

In [10]:
my_array[1:7]

array([    2, 30000,     4,     5])

In [11]:
my_array[-1]

5

In [12]:
my_array.shape

(5,)

In [13]:
my_array.dtype

dtype('int32')

In [14]:
new_array=np.array([1,2,3,400000,5,6] , np.int64)


In [15]:
new_array

array([     1,      2,      3, 400000,      5,      6], dtype=int64)

In [16]:
new_array[0]=20

In [17]:
new_array

array([    20,      2,      3, 400000,      5,      6], dtype=int64)

# array creation : conversion from other python structure

In [18]:
import numpy as np

In [19]:
listarray=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [20]:
listarray

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [21]:
listarray.dtype

dtype('int32')

In [22]:
listarray.shape

(3, 3)

In [23]:
listarray.size

9

In [24]:
zeros=np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
type(zeros)

numpy.ndarray

In [27]:
zeros.dtype

dtype('float64')

The numpy.arange() function is used to generate an array with evenly spaced values within a specified interval.
The function returns a one-dimensional array of type numpy.ndarray.

In [28]:
a_range=np.arange(1,10)    #its arange function work like range but more faster

In [29]:
a_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a_range=np.arange(10)      

In [31]:
a_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number.

In [75]:
lspace=np.linspace(1,10,5)     # 1 to 10 number print , with 5 space 

In [76]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
lspace=np.linspace(1,5,5)

In [35]:
lspace

array([1., 2., 3., 4., 5.])

numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values. Parameters 

In [36]:
emp=np.empty(45)

In [37]:
emp

array([6.79382688e-312, 6.95279840e-310, 6.79382688e-312, 6.95279840e-310,
       6.79382688e-312, 6.95279840e-310, 6.79382688e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382686e-312, 6.95279840e-310,
       6.79382687e-312, 6.95279840e-310, 6.79382687e-312, 6.95279840e-310,
       6.79372780e-312])

numpy.empty_like(a, dtype = None, order = ‘K’, subok = True) : Return a new array with the same shape and type as a given array.

In [77]:
empty_like=np.empty_like(lspace)

In [78]:
empty_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
arr=np.arange(93)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92])

In [43]:
arr.size

93

In [44]:
arr.shape

(93,)

In [45]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [46]:
ar=np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ar.sum(axis=0)

array([12, 15, 18])

In [49]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
ar.flat

In [51]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


# SLICING

In [52]:
import numpy as np

In [53]:
arr[::-1]

array([92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76,
       75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59,
       58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92])

In [55]:
arr[1:5]                                           # [start:end]

array([1, 2, 3, 4])

In [56]:
arr[::-1]

array([92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76,
       75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59,
       58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [57]:
arr=np.array([1,2,3,4,5,6,7,8])

In [58]:
arr[  0     :  4     :2]     #   [start :end :steps]

#   start  :  end   :step

array([1, 3])

In [59]:
import numpy as np

In [60]:
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(arr.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


sorting in numpy

puting element in ordered sequence

In [61]:
import numpy as np 


In [62]:
arr=[2,1,3,5,1,5,7,9,4,1,2,5,1]
print(np.sort(arr))

[1 1 1 1 2 2 3 4 5 5 5 7 9]


you can sort string data type

In [63]:
st=["akash","abhijeet","akshada","venktesh","anushka","ajay","swapnil"]
print(np.sort(st))

['abhijeet' 'ajay' 'akash' 'akshada' 'anushka' 'swapnil' 'venktesh']


filter array 

In [64]:
new_array=np.array([1,2,3,4])


In [65]:
new_array

array([1, 2, 3, 4])

In [66]:
x=[True,False,True,False]

In [67]:
new_filtered_array=new_array[x]

In [68]:
new_filtered_array

array([1, 3])

gererate randon integer element

In [69]:
from numpy import random


In [70]:
#for generate random integer element use randint function

In [71]:
x=random.randint(100,size=(5))

In [72]:
print(x)

[60 37  9 58 13]


In [73]:
#for generate random float element use rand function 


In [82]:
float_random_element=random.rand(100)

In [83]:
float_random_element

array([0.17096021, 0.14454026, 0.88749502, 0.63141294, 0.94009055,
       0.17017138, 0.63406335, 0.21220251, 0.4730018 , 0.69514265,
       0.54117615, 0.73878672, 0.17252656, 0.19920128, 0.61861789,
       0.70157189, 0.01237861, 0.15149812, 0.68673661, 0.76390003,
       0.10229937, 0.45550957, 0.42718904, 0.58513791, 0.08077365,
       0.22638769, 0.06236392, 0.85622891, 0.13749553, 0.29424317,
       0.81428915, 0.4464455 , 0.79904301, 0.87515765, 0.88494463,
       0.38326647, 0.30420765, 0.45655427, 0.76449899, 0.30225343,
       0.21301483, 0.50059155, 0.31888101, 0.4371441 , 0.70109469,
       0.94960551, 0.15153524, 0.94499542, 0.56110545, 0.18792879,
       0.69876908, 0.23889121, 0.93319816, 0.68113592, 0.28668346,
       0.48360207, 0.01308639, 0.05144205, 0.77466044, 0.87261176,
       0.38270114, 0.84730413, 0.96057226, 0.30362748, 0.53374909,
       0.67855943, 0.6066019 , 0.29919049, 0.34389189, 0.31730759,
       0.58802311, 0.280327  , 0.4333668 , 0.31201027, 0.86122

In [ ]:
#create 2-d array using numpy random functio

In [ ]:
from numpy import random

In [ ]:
two_d_array=random.randint(100,size=(5,6))

In [ ]:
two_d_array

In [ ]:
np.sort(two_d_array)

choice () method

In [ ]:
#the choice method allows you to choose random value from your array

In [ ]:
from numpy import random 

In [ ]:
choose_random=random.choice([2,3,4,5,6,7])

In [ ]:
choose_random

In [ ]:
choose_random

In [ ]:
choose_random

In [ ]:
#mixture of choice() and size() method.

In [ ]:
x=random.choice([1,3,4,6,8,9] , size=(3,4))

In [ ]:
x

In [ ]:
print(np.sort(x))    #here i just sort random choose 

# Data Science Batch 

In [ ]:
# Numpy arrays 

In [ ]:
#homogeneous -- its have same data type
#hetrogeneous --- its have different data type 

#numpy is homogeneous

In [ ]:
import numpy as np

In [ ]:
 a=np.array([[2,5,3],[2,5,9]])

In [ ]:
print(a.shape)

In [ ]:
print(a.size)

In [ ]:
print(a.ndim)

In [ ]:
arr=np.array([[2,2],[2,2]])

In [ ]:
arr.shape

In [ ]:
arr

In [ ]:
arr=np.array([[2,2,3],[2,2,3],[1,2,3]])

In [ ]:
arr.shape

In [ ]:
print(arr)

In [ ]:
arr.ndim

In [ ]:
#3 dimention array

arr=np.array([[[1,2],[1,2]],[[1,2],[1,2]]])

In [ ]:
arr.shape

In [ ]:
arr

In [ ]:
arr=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [ ]:
arr.shape

In [ ]:
arr=np.array([[[11,22,13],[31,52,23]],[[61,22,83],[91,22,13]],[[13,24,32],[17,21,36]]])

In [ ]:
print(arr)

In [ ]:
arr.ndim

In [ ]:
lst=[3,4,5,6]
a=np.array(lst)
print(a) 

In [ ]:
lst=[3,4,"hello",(5,6)]
a=np.array(lst,dtype='object')
print(a) 

In [ ]:
a=np.array([[1,2],[9]])
print(type(a),a)

In [ ]:
conda update jupyter

In [ ]:
import numpy as np
a=np.ones((5,5))
print(a)

In [ ]:
a=np.full((5,2),9)
print(a)

In [ ]:
a=np.eye((1),(4),k=2)
a

In [ ]:
arr=np.array([[[11,22,13],[31,52,23]],[[61,22,83],[91,22,13]],[[13,24,32],[17,21,36]]])
print(arr)

In [ ]:
arr[0][1][1]     #indexing

In [ ]:
#slicing

arr[:,0,1]

In [ ]:
e=np.random.randint((1,5))


In [ ]:
e

In [ ]:
e

In [ ]:
e

In [ ]:
a=np.array([[1,2,3,9],[4,5,6,3],[9,0,9,8]])

In [ ]:
b=a[:2,1:3]

In [ ]:
b

In [ ]:
print(a[0:1])

In [ ]:
b[0,0]=9

In [ ]:
b

In [ ]:
a

In [ ]:
row_1=arr[1,:]
row_2=arr[1:2,:]
print(row_1.shape,row_1)
print(row_2.shape,row_2)

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])

In [ ]:
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([0,2,0,1])
a[np.arange(4),b] +=10
print(a)

In [ ]:
a.shape

In [ ]:
a[[0,1,2,3],[0,2,0,1]]    #indexing 

In [ ]:
a

In [ ]:
print(a[0][0],a[1][2],a[2][0],a[3][1])

In [ ]:
 a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(a[bool_idx])
print(bool_idx)

In [ ]:
x=np.array([1,2],'int64')
print(x.dtype)
print(x)

In [ ]:
x=np.array([1.9,2.9],'float32')
print(x.dtype)
print(x)

In [ ]:
x=np.array([1j,2j])# complex number must have i or j example===(1j) or (1i)
print(x.dtype)            
                            #compex array cant convert into integer or float  
print(x)

In [ ]:
x=np.array([1.9,2.9],'complex128')    # float can convert comlex or integer
print(x.dtype)
print(x)

In [ ]:
x=np.array([1,2],'complex')                 #integer and float both are flexible they can conver ito another type 
                                              
print(x.dtype)
print(x)

In [ ]:
x=np.array([1,2.3,2j])                 #complex values use with another data type then all array makes automatically complex
print(x.dtype)
print(x)

In [ ]:
a=np.arange(6)
a2=a[:,np.newaxis]
print(a.shape)
print(a2.shape,a2)


In [ ]:
print(a)

In [ ]:
print(a2)

In [ ]:
a=np.arange(6)
a2=a[np.newaxis,:]       #newxis just add a dimension in array
print(a.shape)
print(a2.shape,a2)


In [ ]:
a2.ndim

In [ ]:
a.ndim

In [ ]:
np.ones(2)                           #it is print one  

In [ ]:
x=np.empty(2)                          #it is print random value

In [ ]:
np.zeros((2,3))

In [ ]:
np.arange(2,8,2)                     #arange fonction print values 2 to 8 and , 2 is gives steps 

In [ ]:
np.linspace(0,10 , num=5,dtype='int8')        

In [ ]:
arr=np.array([2,3,4,5,3,1,3])


In [ ]:
np.sort(arr)


In [ ]:
a=np.array([[5,2],[3,7]])

In [ ]:
np.sort(a,axis=0)

In [ ]:
x=np.sort(a,axis=0)

In [ ]:
np.sort(a,axis=1)

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate([a,b],axis=0)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.concatenate([a,b],axis=0)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.concatenate([a,b],axis=1)

In [ ]:
a=np.array([0,1,2,3,4,5])
b=a.reshape(3,2)

In [ ]:
print(b)

In [ ]:
b=a.reshape(3,2,1)

In [ ]:
b

In [ ]:
b.shape

In [ ]:
a=np.array([1,2,3,4,5,6])
a.shape

you can use np.expand_dims to add at index position 

In [ ]:
b=np.expand_dims(a,axis=1)

In [ ]:
b.shape

In [ ]:
b=np.expand_dims(a,axis=0)

In [ ]:
b.shape

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
div_by_2=a[a%2==0]
print(div_by_2)

In [ ]:
b=np.nonzero(a<5)                    #ith normally a variable madhil non zero asnari value greater then 5 asal tyachi indexin
print(b)

In [ ]:
a=np.arange(1,13).reshape(6,2)

In [ ]:
print(a)

In [ ]:
list_of_cordinate=list(zip(b[0],b[1]))
for i in list_of_cordinate:
    print(i)

In [ ]:
np.array([1,2,3,4,5,5]).reshape(2,3)

In [ ]:
x=np.array([2,3,1,7,3,9,4])
c=np.nonzero(x<5)
print(c)

In [ ]:
a=[1,2,3,4]
b=["num","num","num","num"]
for i in zip(a,b):
    print(i)

In [ ]:
import numpy as np

In [ ]:
a1=np.array([[1,1],[1,2]])
a2=np.array([[3,3],[4,4]])

In [ ]:
np.vstack((a1,a2))

In [ ]:
np.hstack((a1,a2))

In [ ]:
x=np.arange(1,25).reshape(2,12)

In [ ]:
x

In [ ]:
a=np.hsplit(x,3)

In [ ]:
a

In [ ]:
type(a)

In [ ]:
x=np.arange(1,37).reshape(6,6)
x=np.hsplit(x,3)
x

In [ ]:
x=np.arange(1,25).reshape(4,6)
x=np.vsplit(x,4)
x

In [ ]:
x=np.arange(1,37).reshape(6,6)
x=np.hsplit(x,(2,4))
x

In [ ]:
data=np.array([1,2])
data1=np.ones(2)
data+data1

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [ ]:
print(x.dot(y))

In [ ]:
x@y

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x)    #create a empty matrix with the same shape as x

In [ ]:
print(y)

In [ ]:
x

In [ ]:
for i in range(3):
    y[i:]=x[i,:]+v
print(y)

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
vv=np.tile(v,(4,1)) 
print(vv)

In [ ]:
y=x+vv

In [ ]:
y

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
list(np.broadcast(x,y))

In [ ]:
x=np.arange(5)

In [ ]:
x[::-1]

In [ ]:
z=np.arange(16).reshape(4,4)

In [ ]:
z

In [ ]:
nz=np.nonzero([1,2,0,0,4,0])     #its give a position of non zero value 

In [ ]:
nz

In [ ]:
z=np.random.random((10,10))   #10 rows and 10 column
zmin,zmax=z.min(),z.max()

In [ ]:
print(zmin,zmax)

In [ ]:
x=np.ones((3,3))
x[1,1]=0
x

In [140]:
a=np.zeros((6,6),'int32')

In [146]:
a[1:-1,1:-1]=1

In [147]:
a

array([[0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [143]:
a=np.ones((6,6),'int32')

In [144]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [145]:
a[::2,::2]=0
a[1::1,1::2]=0

In [139]:
a

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0]])

In [119]:
z =np.ones((5,5))
z=np.pad(z,pad_width=3,mode='constant',constant_values=0)

In [120]:
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [121]:
0*np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set ([np.nan])
0.3 ==3 * 0.1

False

In [122]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [123]:
x=np.ones((8,8),'int8')

In [124]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [127]:
x=np.array([np.arange(336)]).reshape(6,7,8)

In [128]:
x

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [129]:
pos=np.unravel_index(99,(6,7,8))                           

In [130]:
pos

(1, 5, 3)

checkerboard 8 by 8 matrix using the tile function

In [131]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))

In [132]:
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [133]:
z.shape

(8, 8)

In [149]:
z=np.random.random((5,5))
z=(z-np.mean(z) / np.std(z))
print(z)

[[-1.15171771 -1.08377436 -1.05876366 -0.73588589 -1.10461881]
 [-1.29923054 -1.55073376 -1.36791783 -1.37978827 -0.88033838]
 [-1.2274541  -1.12120765 -1.16245227 -1.61624648 -1.62248678]
 [-1.0779482  -1.13028049 -1.33937501 -0.76622002 -0.66074513]
 [-0.94708516 -1.23284032 -1.59960986 -0.90472761 -1.62859026]]


In [135]:
z=np.random.random((5,5))
z

array([[0.44777807, 0.61557157, 0.47233835, 0.73548055, 0.99514897],
       [0.09927386, 0.1800513 , 0.78549254, 0.43521311, 0.26263984],
       [0.72735746, 0.82749204, 0.64821967, 0.27723167, 0.04106362],
       [0.72672753, 0.42350153, 0.21048123, 0.23276604, 0.72933288],
       [0.19773063, 0.75506863, 0.96261162, 0.57840962, 0.55045597]])